# Site settings
title: My Journey to Data Science
name: My Journey to Data Science
header-img: img/home-bg.jpg
email: pds.bangalore@gmail.com	
description: "My experiments and learnings in Data Science"
baseurl: ""
#url: "http://ds.gregvi.al"
#twitter_username: 
github_username:  sahoopa
#facebook_username:  
linkedin_username: in/pallavisahoo
#email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id: UA-86523398-1

# Build settings
markdown: kramdown
encoding: UTF-8
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
